- name: 铁甲小宝
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=tjxb

- name: 犬夜叉
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=qyc

- name: AA 3.5.0.0 - Playwith Taiwan
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=aa-part

- name: 使命召唤20 现代战争3
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=Call.of.Duty.Modern.Warfare.III.Campaign.Only-InsaneRamZes

- name: Win10_LTSC_OVA
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=Win10_LTSC_OVA

- name: windows_7
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso

- name: Win10_LTSC
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=cn_windows_10_enterprise_ltsc_2019_x64_dvd_d17070a8.iso

- name: Win11_LTSC
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.iso

- name: javascript-tutorial
- url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=javascript-tutorial

