- name: AA 3.5.0.0 - Playwith Taiwan
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=aa-part

- name: 使命召唤20 现代战争3
  url: https://hub.docker.com/r/sjwayrhz/docker/tags?name=Call.of.Duty.Modern.Warfare.III.Campaign.Only-InsaneRamZes